<?php

namespace Database\Seeders;

use App\Models\Namelist;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Str;

class NamelistCowok extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [


            [
                'full_name' => 'Abbad Nailun Nabhan',
                'meaning' => 'Laki-laki yang rajin beribadah dan mendapat kemuliaan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Abu Bakr As-Siddiq',
                'meaning' => 'Sahabat pertama yang memeluk Islam',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Abdiel Justin Gilbert',
                'meaning' => 'Hamba Allah yang adil dan dapat terpercaya',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Abdullah Saad Abbas',
                'meaning' => 'Hamba Allah yang memiliki keberuntungan dan keberaniannya seperti singa',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Abdullah Al-Malikul Quddus',
                'meaning' => 'Hamba Allah yang mulia, pemilik kesucian',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Addar Quthni Poldi',
                'meaning' => 'Sosok imam perawi hadits yang sangat berani',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Adib Alim Aminullah',
                'meaning' => 'Laki-laki berilmu dan beradab yang mendapat kepercayaan dari Allah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Afif Ahwal Said',
                'meaning' => 'Laki-laki yang memelihara diri dari perbuatan terlarang dan keadaannya selalu bahagia',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Afnan Atma Purnama',
                'meaning' => 'Laki-laki yang memiliki jiwa mekar berseri seperti cahaya rembulan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ahmad Al-Fattah Ar-Rahman',
                'meaning' => 'Yang terpuji, pembuka segala rahmat',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Akmal Umar Zuhair',
                'meaning' => 'Laki-laki yang sempurna dan panjang umur',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ammar Fathee Karim',
                'meaning' => 'Sosok pemimpin yang murah hati dan panjang umur',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Arham Mian Zayan',
                'meaning' => 'Anak laki-laki yang dihormati, baik dan tampan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Danish Farhan Asad',
                'meaning' => 'Anak laki-laki yang bahagia, beruntung, dan bijak',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],



            [
                'full_name' => 'Alim Shafiyyur Rahman',
                'meaning' => 'Laki-laki yang cerdas, pintar, dan lembut',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ararya Saguna Amrullah',
                'meaning' => 'Laki-laki bangsawan yang selalu mentaati perintah Allah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Aqlan Harith Ridauddin ',
                'meaning' => 'Laki-laki bijaksana yang selalu berusaha mencari keridhaan agama',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Azraqi Nabil Imtiaz',
                'meaning' => 'Bayi laki-laki yang pintar dan memiliki keistimewaan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Adzriel Nuraz Rahman',
                'meaning' => 'Laki-laki yang baik dan penuh welas asih',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Arfadhia Fauhad Suleiman',
                'meaning' => 'Laki-laki yang terhormat, pembawa kedamaian dan ketenangan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Aslan Maula Ashaz',
                'meaning' => 'Lelaki yang penuh keberanian dan baik hati',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Azka Fahri Rashid',
                'meaning' => 'Pemimpin terbaik yang adil dan dihormati',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Azraqi Razzan Maalik',
                'meaning' => 'Laki-laki yang berwibawa',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],



            [
                'full_name' => 'Bari Abdul Jalil',
                'meaning' => 'Seorang hamba Allah yang pandai dan mulia',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Basil Basyiruddin',
                'meaning' => 'Laki-laki pemberani pengantar berita baik tentang agama',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Beryl Hamizan Rabbani',
                'meaning' => 'Laki-laki yang seperti permata berharga, memiliki kecerdasan, serta arif dan saleh',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Billal Hafizh Athaillah',
                'meaning' => 'Rahmat Allah yang bertanggung jawab',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Daffa Muhammad Nafil',
                'meaning' => 'Laki-laki yang berakhlak terpuji dan selalu dirahmati Allah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Dawas Said Bareeq',
                'meaning' => 'Sosok pemberani yang dianugerahi kilau kebahagiaan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Dilfa Barqi Abbasy',
                'meaning' => 'Pria pemberani sekaligus lincah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Farras Barra Muayyad',
                'meaning' => 'Sosok cerdas dan independen yang dilindungi Allah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Faris Miqdad Nazeeh',
                'meaning' => 'Ksatria penjaga yang menjauhi dari hal-hal tidak terpuji',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Fawwas Hamzah Antar',
                'meaning' => 'Sosok pemberani yang selalu menang dalam peperangan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Fathian Wafi Serhan',
                'meaning' => 'Anak laki-laki yang mendapat kemenangan, kekuasaan dan penuh keyakinan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Faiz Hafiz Asnawi',
                'meaning' => 'Lelaki yang murah hati dan penuh tanggung jawab',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Fauzil Syafi Artanabil',
                'meaning' => 'Lelaki yang bijaksana dan penuh keteguhan hati',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Fadhilur Rahim Al-Ghafur',
                'meaning' => 'Yang mulia, yang penyayang, yang pemaaf',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],



            [
                'full_name' => 'Gaishan Raffasya Hafis',
                'meaning' => 'Laki-laki tampan yang memiliki kedudukan tinggi dan selalu melindungi banyak orang',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ghifari Syafi Muzakki',
                'meaning' => 'Anak Laki-laki yang dilahirkan dengan kelembutan hati, dan menjadi penolong bagi orang lain',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Hanif Yasser Syathibi',
                'meaning' => 'Laki-laki yang memiliki tekad dan kemauan untuk menjadi ulama dengan kemuliaan besar',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Hafizhan Raffa Khairy',
                'meaning' => 'Laki-laki yang memiliki banyak kebaikan, selalu terlindung dan penuh kebahagiaan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Jafar Rakha Mubasyir',
                'meaning' => 'Pemberi kabar baik yang hidupnya dipenuhi kemuliaan dan kekayaan yang berlimpah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Jiyad Umar Hafie',
                'meaning' => 'Sosok yang baik dan dermawan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],



            [
                'full_name' => 'Khaleed Sharim Mudzafar',
                'meaning' => 'Sosok pemberani dan pandai berbicara',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Kahill Abedin Rashad',
                'meaning' => 'Teman baik yang alim dan penuh integritas',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Khairul Basyar Ash-Shafi',
                'meaning' => 'Sebaik-baik manusia, Yang Maha Menyembuhkan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Keenan Ghazi Utsman',
                'meaning' => 'Ksatria pelindung',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Khaleel Houd Nabeeh',
                'meaning' => 'Seorang sahabat yang terhormat',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Liham Syubbanul Yaum',
                'meaning' => 'Anak lelaki yang memiliki banyak harapan di masa muda',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Lutfi Nabil Zaroon',
                'meaning' => 'Anak lelaki yang selalu halus tutur katanya',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Lukman Kaiser Zaydan',
                'meaning' => 'Anak lelaki yang patuh pada perintah Allah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Mahmud Husain Zahidi',
                'meaning' => 'Sosok yang terpuji, takwa, dan baik di dunia',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Malikul Mulk Iman',
                'meaning' => 'Pemilik kerajaan yang beriman',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Mauza Liban Aldebaran',
                'meaning' => 'Laki-laki yang baik hati dan jadi panutan banyak orang',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Marwan Zabdan Muzakki',
                'meaning' => 'Anak lelaki yang hati lurus, suci bersih dan diberi anugerah oleh Allah.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Mu’thi Badruz Zaman',
                'meaning' => 'Sosok yang selalu memberi dan menjadi lampu penerang kehidupan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Muhammad Adib Ansharri',
                'meaning' => 'Anak yang baik budinya dan penyayang kepada sesama',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Muhammad Anshary Amrullah',
                'meaning' => 'Laki-laki yang sangat terpuji, selalu memperoleh pertolongan Allah dan menaati perintah-Nya',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Muhammad Iman Kamil',
                'meaning' => 'Laki-laki yang sangat terpuji dan punya iman sempurna',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Munifun Aliyul Wafi',
                'meaning' => 'Laki-laki yang tinggi kedudukannya dan terkenal karena kesempurnaan akhlak',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Miftahurrahman Ash-Shofi',
                'meaning' => 'Laki-laki bercahaya yang tidak memiliki cacat sebagai perantara berkah dari Allah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Mutawakkilu Alal Malik',
                'meaning' => 'Orang yang mengandalkan Tuhan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],



            [
                'full_name' => 'Nail Nabil Amru',
                'meaning' => 'Orang yang mulia dan panjang umur',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Nawwar Antarun Asady',
                'meaning' => 'Laki-laki pemberi cahaya kebaikan dan berani bagaikan singa',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Nadeem Abul Khayr',
                'meaning' => 'artinya adalah bayi laki-laki Islam yang bersahabat dan suka berbuat kebaikan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Naufal Muadz Baqir',
                'meaning' => 'Sosok yang tampan, seseorang yang memiliki pengetahuan luas, dan terpelihara dengan baik',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Nibras Zubair Shadeeq',
                'meaning' => 'Orang yang berani dan jujur',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Qomar Hamizah Gemilang',
                'meaning' => ' Laki-laki yang tampan seperti bulan yang terang',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Rafa Fauzan Kamil',
                'meaning' => 'Sosok yang dikenal karena memiliki sifat-sifat baik serta sempurna',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Rafi Shameed Anas',
                'meaning' => 'Sahabat nabi yang memiliki kedudukan tinggi',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Raif Althaf Hasan',
                'meaning' => 'Sosok yang lembut dan penuh kasih sayang',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Rasyiqul Abid Abdullah',
                'meaning' => 'Hamba Allah yang gagah dan rajin beribadah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Rashid Abdul Razaaq',
                'meaning' => 'artinya sang hamba yang berjalan di jalan kebenaran',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Razzan Yazid Nizam',
                'meaning' => 'Laki-laki yang berwibawa, disiplin dan dirahmati Allah.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Razqa Nabil Arfadhia',
                'meaning' => 'Anak lelaki yang banyak rezeki, cerdas dan terpandang',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Rasya Derya Arrazi',
                'meaning' => 'Anak laki-laki yang sejahtera dan memiliki keluasan hati',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Rayyan Jahi Abizar',
                'meaning' => 'Laki-laki yang tampan dan berakhlak terpuji',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Rashid Amir Daniyal',
                'meaning' => 'Pangeran yang pintar dan dipandu oleh Allah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Saad Ilham Fakhruddin',
                'meaning' => 'Anak lelaki sumber kebahagiaan dan kebanggaan di dalam agama Islam',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Shahbaz Ayman Ahsan',
                'meaning' => 'Anak laki-laki yang berani, beruntung dan baik',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zian Imran Ali',
                'meaning' => 'Anak laki-laki yang tampan, terkenal dan berbahagia',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],



            [
                'full_name' => 'Shadiq Musthafa Karim',
                'meaning' => 'Laki-laki terpilih yang mulia dan bisa dipercaya',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => '&nbsp;Taqiuddin Uzmatur Rahman',
                'meaning' => 'Laki-laki yang baik bertaqwa dalam ajaran agama mendapat keagungan dari Allah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Tsaqib Naufal Ziyad',
                'meaning' => 'Laki-laki yang beruntung dan bertumbuh cepat',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ulya Aziz Tamam',
                'meaning' => 'Laki-laki yang berkedudukan mulia, perkasa, dan sempurna',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Yaqdhan Rakha Assaid',
                'meaning' => 'Pria yang memiliki kehidupan bahagia',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zhafran Afkari Muslim',
                'meaning' => 'Laki-laki yang beruntung, bijaksana dan penuh keyakinan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zharif Nawaf Mushab',
                'meaning' => 'Sahabat nabi yang pintar',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zaid Hafi Ihsan',
                'meaning' => 'Seseorang yang baik hati',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zakwan Keven Hafizh',
                'meaning' => 'Sosok laki-laki penghafal Al quran yang cerdik dan tampan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zayyan Zainul Muttaqin',
                'meaning' => 'Laki-laki yang berwajah tampan yang seperti perhiasan bagi orang bertaqwa',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zahid Hamizan Rabbani',
                'meaning' => 'Laki-laki yang rendah hati, cerdas, arif, dan saleh',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zaidan Hasan Fann',
                'meaning' => 'Laki-laki yang memiliki banyak kelebihan dalam kebaikan dan seni',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zarrar Nabil Alfarizqi',
                'meaning' => 'Anak lelaki yang pemberani, cerdas dan pembawa rezeki',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Zimam Daffa Muzakki',
                'meaning' => 'Laki-laki yang punya kekuasaan dan berhati bersih',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],



            [
                'full_name' => 'Cleine Thanos Al Faruq',
                'meaning' => 'Laki-laki yang terkenal mulia sebagai pembeda antara yang haq dengan bathil',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Chairil Rafqi Alfarezel',
                'meaning' => 'Anak laki-laki yang memiliki kelembutan hati dan selalu menyebarkan kebaikan di dalam hidupnya.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Charemon Abdul Hafiz',
                'meaning' => 'Laki-laki yang memiliki semangat bergembira menjadi hamba Allah yang terpelihara',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Chairil Mihran Ghazzal',
                'meaning' => 'Anak laki-laki baik hati yang memiliki sifat seperti sahabat Rasulullah SAW dan diharapkan bisa menjadi ahli Al-Qur’an.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Carim Basim Elfathan',
                'meaning' => 'Anak dermawan yang selalu tersenyum dan mendapat kemenangan dari Allah.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Chumaidi Dzafri Farraz',
                'meaning' => 'Anak laki-laki yang dipuja dan bersinar karena karena kejujurannya.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Efendi Mufid Mu’tashim',
                'meaning' => 'Laki-laki dengan kebahagiaan dan kecintaan suci yang dapat memberikan manfaat.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Emyr Salim Hauzan',
                'meaning' => 'Manusia yang mulia dan terhindar dari bencana.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ezar Faruq Khattab',
                'meaning' => 'Laki-laki yang sangat berharga dan menjadi pengkhotbah tentang pembeda kebaikan dan keburukan kehidupan.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ezar Zhafar Dhiaurrahman',
                'meaning' => 'Kemenangan anak laki-laki yang sangat berharga karena sifatnya penuh kasih.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Istaz Qasim Maulana',
                'meaning' => 'Pendakwah yang elok dan dihormati.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'I’timad Ibadil Kiram',
                'meaning' => 'Laki-laki yang menjadi sandaran hamba-hamba-Nya yang mulia.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ibni Badruddin Wanasim',
                'meaning' => 'Anakku laksana bulan purnama agama (memancarkan cahaya iman) memberi kesejukan bagai angin sepoi-sepoi',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ihsan Rasyid Ridhwan',
                'meaning' => 'Laki-laki yang jiwa raganya sehat mencintai kebaikan dan memperoleh keridaan Tuhan.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ikhbar Shaqr Akhdan',
                'meaning' => 'Sahabat yang menyampaikan berita dan tajam penglihatannya.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ikram Nabil Naufal',
                'meaning' => 'Laki-laki terhormat yang memiliki kepandaian dan senantiasa mengulurkan pertolongan.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Istaz Qasim Maulana',
                'meaning' => 'Pendakwah yang elok dan dihormati.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Imam Ayatullah Khumaini',
                'meaning' => 'Laki-laki yang menjadi pemimpin berwawasan luas dengan berpegang kepada ayat-ayat Allah.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Imtiyaz Insan Kamil',
                'meaning' => 'Laki-laki yang punya keistimewaan sebagai manusia sempurna.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Istaz Qasim Maulana',
                'meaning' => 'Pendakwah yang elok dan dihormati',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Omri Emery Prasetya',
                'meaning' => 'Laki-laki yang selalu menepati janjinya dengan hati yang baik, teguh dan diberkati umur panjang oleh Tuhan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Obaid Nandana Cahyadi',
                'meaning' => 'Laki-laki yang berparas indah, tampan, dan kelak menjadi seorang anak yang saleh serta terpuji.',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Prima Athmar Abdul Ghani',
                'meaning' => 'Laki-laki yang utama menjadi hamba yang kaya dan berjaya',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Pasya Saquell Syazani Althfurrahman',
                'meaning' => 'Anak laki-laki yang tampan, cerdas, pemurah dan baik hati seperti seorang Raja',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Pervaiz Haikal Narayana',
                'meaning' => 'Anak yang selalu menyebarkan kebaikan dan memiliki kebesaran di dalam hatinya',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],



            [
                'full_name' => 'Qaisar Muhammad Naufal',
                'meaning' => 'Raja yang terpuji dan tampan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Qaidu Shidiq Mushaffa',
                'meaning' => 'Laki-laki yang memimpin kebenaran yang murni',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Qaisar Muhammad Naufal',
                'meaning' => 'Raja yang terpuji dan tampan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Shabir Ahmad Shadiq',
                'meaning' => 'Laki-laki terpuji yang penyabar dan amanah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Sa’di Khairul Anam',
                'meaning' => 'Laki-laki yang bahagia dari sebaik-baik manusia',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Sakha Ibadil Kiram',
                'meaning' => 'Laki-laki dermawan sebagai hamba Allah yang mulia',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Saskara Akbar Fathul Islam',
                'meaning' => 'Laki-laki dengan kebenaran dan kemurnian yang besar sebagai pembuka kejayaan Islam',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Shabri Sirajul Qalb',
                'meaning' => 'Laki-laki penyabar yang menjadi pelita hati',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Shabur Abdur Rahim',
                'meaning' => 'Laki-laki yang penyabar sebagai hamba Allah Yang Maha Pengasih',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Shofi Abdulllah Assunni',
                'meaning' => 'Laki-laki yang jernih hati sebagai hamba Allah yang menjalankan sunnah Rasullullah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Sirajul Huda Mustaqim',
                'meaning' => 'Laki-laki yang lurus menjalankan agama dan jadi petunjuk Allah',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Ulwan Abdun Maimun',
                'meaning' => 'Laki-laki yang tinggi kedudukannya sebagai hamba Allah yang diberkahi',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Wahid Amzar Hafizuddin',
                'meaning' => 'Laki-laki pertama yang mulia serta menjadi pemelihara agama',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Wailullah Ghufranul Ibad',
                'meaning' => 'Laki-laki yang kembali kepada Allah yang memberi ampuna kepada hamba-hamba-Nya',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Wajdi Karimul Huda',
                'meaning' => 'Laki-laki yang penuh cinta dalam petunjuk kemuliaan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Washif Syarif Mubarak',
                'meaning' => 'Laki-laki yang mempunyai karakter mulia dan diberkahi',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Washilullah Qutbul Umam',
                'meaning' => 'Laki-laki penyambung tali kepada Allah yang menjadi pemimpin umat',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Watsiq Dzul Karam',
                'meaning' => 'Laki-laki tentram yang memiliki kemuliaan',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Wafi Rafan Asadel',
                'meaning' => 'Anak laki-laki yang berwajah tampan, sempurna, dan ramah kelak dengan keyakinannya menjadi seseorang yang makmur',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],
            [
                'full_name' => 'Wafi Muzakki Ishak',
                'meaning' => 'Anak laki-laki keturunan Nabi kesembilan yang sempurna dan selalu mengeluarkan zakat',
                'gender_id' => 1,
                'religion_id' => 2,
                'locale' => 'id',
                'status' => 'active',
            ],


        ];

        Namelist::insert($data);
    }
}
