<?php

namespace Database\Seeders;

use App\Models\CategoryArticle;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NewCategoryArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $categories = [
           
            [
                'name' => [
                    'en' => 'News',
                    'id' => 'Berita',
                ],
                'parent_id' => null,
                'description' => null,
            ],
            [
                'name' => [
                    'en' => 'Pregnancy',
                    'id' => 'Kehamilan',
                ],
                'parent_id' => null,
                'description' => null,
            ],
            [
                'name' => [
                    'en' => 'Parenting',
                    'id' => 'Pola asuh',
                ],
                'parent_id' => null,
                'description' => null,
            ],

            [
                'name' => [
                    'en' => 'First Trimester',
                    'id' => 'Trimester Awal',
                ],
                'parent_id' => 2,
                'description' => [
                    'en' => 'In your first trimester of pregnancy? Get tips and information on screenings, symptoms, your baby&#39;s size, weight gain, do&#39;s and don&#39;ts, and miscarriage risk in the first 12 weeks.',
                    'id' => 'Di trimester pertama kehamilan? Dapatkan tips dan informasi tentang skrining, gejala, ukuran bayi, kenaikan berat badan, hal yang boleh dan tidak boleh dilakukan, serta risiko keguguran dalam 12 minggu pertama.',
                ],
            ],
            [
                'name' => [
                    'en' => 'Second Trimester',
                    'id' => 'Trimester kedua',
                ],
                'parent_id' => 2,
                'description' => [
                    'en' => 'In your second trimester of pregnancy? Learn about screenings, ultrasounds, weight gain, fetal development, complications, miscarriage risk, and more in weeks 13 through 25.',
                    'id' => 'Sudah masuk trimester kedua kehamilan? Pelajari tentang skrining, USG, kenaikan berat badan, perkembangan janin, komplikasi, risiko keguguran, dan banyak lagi di minggu ke-13 hingga ke-25.',
                ],
            ],
            [
                'name' => [
                    'en' => 'Third Trimester',
                    'id' => 'Trimester ketiga',
                ],
                'parent_id' => 2,
                'description' => [
                    'en' => 'In your third trimester of pregnancy? As you approach 40 weeks, get tips on your health, weight gain, fatigue, baby size, labor and delivery, and preparing for baby.',
                    'id' => 'Sudah masuk trimester ketiga kehamilan? Saat Anda mendekati usia kehamilan 40 minggu, dapatkan tips tentang kesehatan Anda, kenaikan berat badan, kelelahan, ukuran bayi, persalinan dan melahirkan, serta persiapan menyambut bayi.',
                ],
            ],
            [
                'name' => [
                    'en' => 'Fourth Trimester',
                    'id' => 'Trimester keempat',
                ],
                'parent_id' => 2,
                'description' => null,
            ],
            [
                'name' => [
                    'en' => 'Postportum',
                    'id' => 'Postportum',
                ],
                'parent_id' => 2,
                'description' => null,
            ],

            [
                'name' => [
                    'en' => 'Babies',
                    'id' => 'Bayi',
                ],
                'parent_id' => 3,
                'description' => null,
            ],
            [
                'name' => [
                    'en' => 'Toddlers',
                    'id' => 'Balita',
                ],
                'parent_id' => 3,
                'description' => null,
            ],
            [
                'name' => [
                    'en' => 'Big Kids',
                    'id' => 'Anak kecil',
                ],
                'parent_id' => 3,
                'description' => null,
            ],
            [
                'name' => [
                    'en' => 'Tweens & Teens',
                    'id' => 'Praremaja dan Remaja',
                ],
                'parent_id' => 3,
                'description' => null,
            ],
        ];

        foreach ($categories as $categoryData) {
            CategoryArticle::create($categoryData);
            // The slug will be automatically generated by the HasSlug trait
        }
    }
}
